services:
  graph-node:
    image: graphprotocol/graph-node:v0.35.1
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    expose:
      - 8000
      - 8001
      - 8020
      - 8030
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: ${postgres_pass}
      postgres_db: postgres
      ipfs: 'ipfs:5001'
      # Change next line if you want to connect to a different JSON-RPC endpoint
      ethereum: 'optimism-sepolia:https://bob-sepolia.rpc.gobob.xyz'
      GRAPH_LOG: 'debug'
      # GRAPH_GRAPHQL_QUERY_TIMEOUT: ''
      # GRAPH_SQL_STATEMENT_TIMEOUT: ''
      # GRAPH_GRAPHQL_MAX_DEPTH: ''
      # GRAPH_GRAPHQL_MAX_COMPLEXITY: ''
      GRAPH_ETH_CALL_BY_NUMBER: 1
      GRAPH_NO_EIP_1898_SUPPORT: 1
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 1
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: 1
    restart: ''
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - '5001:5001'
    expose:
      - 5001
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
